Lesson 13
OlehBorodin/nix_solutions pull request #3
Opened 2022-07-22 21:49 UTC by OlehBorodin

pending what needs fixes... :)

2022-07-22 21:57 UTC, Fabolo12 requested changes
Смержи дз которые я принял, а то проверять что ты добавил новое очень трудно

2022-07-22 21:57 UTC, Fabolo12 commented on src/main/java/com/sell/Container.java
> +public class Container {
Класс должен быть параметризирован, а не использовать абстракции

2022-07-22 21:57 UTC, Fabolo12 commented on src/main/java/com/sell/Discount.java
> +public class Discount<T extends Vehicle> {
А в чем разница этого класса и Контейнера?

2022-07-22 21:57 UTC, Fabolo12 commented on src/main/java/com/sell/Discount.java
> +    public void updatePrice(Number X) {
Тут все равно должна быть параметризация

2022-07-22 21:57 UTC, Fabolo12 commented on src/main/java/com/service/AutoService.java
> +    public Optional<Auto> findOneById(String id) {
Можно перенести в абстракцию

2022-07-22 22:06 UTC, OlehBorodin commented on src/main/java/com/sell/Discount.java
> +public class Discount<T extends Vehicle> {
это я с товарищем советовался как сделать и не удалил

2022-07-24 21:36 UTC, Fabolo12 approved these changes

2022-07-24 21:36 UTC, Fabolo12 commented on src/main/java/com/sell/Discount.java
> +    public <O extends Number> void updatePrice(Number X) {
А тут ошибка так и осталась...
` public <O extends Number> void updatePrice(O X) {`

2022-08-05 21:09 UTC, merged